### PR TITLE
[#10] feat(profile): enable heap profile with tikv-jemalloc

### PR DESCRIPTION
**Pull request by advancedxy**

### CODE REVIEW

**Comment by advancedxy** [comment]
@zuston this might be WIP still. But I think you can try to play it when you have some time.

**Comment by advancedxy** [comment]
Notes: the heap dump on Mac OS X doesn't contain/resolve hex address to function names.

**Comment by zuston** [comment]
> Notes: the heap dump on Mac OS X doesn't contain/resolve hex address to function names.

Let me try it.

**Comment by zuston** [comment]
And the CI failed on style check. Please run `cargo fmt`

**Comment by advancedxy** [comment]
> And the CI failed on style check. Please run `cargo fmt`

didn't notice that, updated.

**Comment by advancedxy** [comment]
There's no space left error on Github CI, let me tweak it tonight.

**Comment by zuston** [comment]
$ `cargo build  --features memory-prof`

error: Package `uniffle-x v0.1.0 (/Users/zuston/iqiyiDev/uniffle-x)` does not have feature `tikv-jemallocator`. It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

Could you help me when compiling on mac intel ?

**Comment by advancedxy** [comment]
‘rustup update’，seems like this syntax is only supported in the recent versions.

**Comment by zuston** [comment]
> rustup

Oh yes. I found the `rustc 1.72.0-nightly (f0411ffce 2023-05-30)` is OK . I'm not sure is it right of using the unofficial features in a stable project?

**Comment by advancedxy** [comment]
stable version should do the trick

**Comment by advancedxy** [comment]
> > rustup
> 
> Oh yes. I found the `rustc 1.72.0-nightly (f0411ffce 2023-05-30)` is OK . I'm not sure is it right of using the unofficial features in a stable project?

The CI issue fixed, and I believe the latest stable is sufficient to run current code

**Comment by zuston** [comment]
> > > rustup
> > 
> > 
> > Oh yes. I found the `rustc 1.72.0-nightly (f0411ffce 2023-05-30)` is OK . I'm not sure is it right of using the unofficial features in a stable project?
> 
> The CI issue fixed, and I believe the latest stable is sufficient to run current code

Yes. I will check this in the next 2 days. Thanks for your effort.

**Review by zuston — APPROVED** [review]

**Comment by zuston** [comment]
Have checked. Thanks for you effort @advancedxy

**Pull request merged**
