### PR TITLE
Use once_cell to replace lazy_static macro

### LINKED ISSUE #47: Use once_cell to replace lazy_static macro
The macro is not a good choice, compared with the Once cell crate, which provides the same abilities and has been adapted with the tokio project.

### PR DESCRIPTION
**Pull request by pegasas**

### CODE REVIEW

**Comment by pegasas** [comment]
try to resolve https://github.com/zuston/riffle/issues/47

**Review by zuston — APPROVED** [review]
LGTM. Thanks for your contribution~

**Comment by zuston** [comment]
if you don't mind, please run the `cargo fmt` @pegasas

**Comment by pegasas** [comment]
> if you don't mind, please run the `cargo fmt` @pegasas

Sure. 

Done.

**Pull request merged**
